[package]
name = "protobuf_reflection"
version = "0.1.0"
edition = "2021"

[lib]
name = "protobuf_reflection"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
flutter_rust_bridge = "1.20.1"
protobuf = "3.0.0-alpha.6"
protobuf-parse = "3.0.0-alpha.6"
